# tests/test_archmap.py
"""Tests for archmap: stdlib ast import walk -> mermaid module graph."""
import logging
import os

from kickass_loop_engineer.archmap import module_graph, to_mermaid, write_archmap


def _fixture_pkg(tmp_path):
    """A 3-module package with internal imports in both forms + externals."""
    pkg = tmp_path / "pkg"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    (pkg / "a.py").write_text("import os\nfrom .b import helper\n")
    (pkg / "b.py").write_text("import re\nimport json\n\nhelper = 1\n")
    (pkg / "c.py").write_text(
        "import pkg.a\nfrom pkg import b\nimport collections.abc\n")
    return tmp_path


def test_module_graph_collects_exactly_the_internal_edges(tmp_path):
    edges = module_graph(str(_fixture_pkg(tmp_path)))
    assert edges == [("pkg.a", "pkg.b"), ("pkg.c", "pkg.a"), ("pkg.c", "pkg.b")]


def test_module_graph_excludes_stdlib_and_external_imports(tmp_path):
    edges = module_graph(str(_fixture_pkg(tmp_path)))
    for src, dst in edges:
        assert src.startswith("pkg")
        assert dst.startswith("pkg")


def test_module_graph_detects_src_layout(tmp_path):
    nested = tmp_path / "ws"
    nested.mkdir()
    _fixture_pkg(nested)
    (nested / "pkg").rename(nested / "renamed")  # move aside
    src = nested / "src"
    src.mkdir()
    (nested / "renamed").rename(src / "pkg")
    edges = module_graph(str(nested))
    assert ("pkg.a", "pkg.b") in edges


def test_syntax_error_file_skipped_with_warning(tmp_path, caplog):
    root = _fixture_pkg(tmp_path)
    (root / "pkg" / "bad.py").write_text("def broken(:\n")
    with caplog.at_level(logging.WARNING):
        edges = module_graph(str(root))
    assert edges == [("pkg.a", "pkg.b"), ("pkg.c", "pkg.a"), ("pkg.c", "pkg.b")]
    assert any("bad.py" in record.getMessage() for record in caplog.records)


def test_module_graph_empty_for_tree_without_package(tmp_path):
    (tmp_path / "notes.txt").write_text("no python here")
    assert module_graph(str(tmp_path)) == []


def test_to_mermaid_sanitizes_ids_and_keeps_dotted_labels():
    text = to_mermaid([("pkg.a", "pkg.b")])
    assert text.startswith("graph TD")
    assert 'pkg_a["pkg.a"] --> pkg_b["pkg.b"]' in text


def test_write_archmap_writes_docs_file_with_header(tmp_path):
    root = _fixture_pkg(tmp_path)
    path = write_archmap(str(root))
    assert path == os.path.join(str(root), "docs", "architecture.mermaid.md")
    content = open(path, encoding="utf-8").read()
    assert "generated by" in content.lower()
    assert "```mermaid" in content
    assert "graph TD" in content


def test_write_archmap_regenerates_instead_of_appending(tmp_path):
    root = _fixture_pkg(tmp_path)
    write_archmap(str(root))
    path = write_archmap(str(root))
    content = open(path, encoding="utf-8").read()
    assert content.count("graph TD") == 1


def test_write_archmap_returns_none_without_package(tmp_path):
    assert write_archmap(str(tmp_path)) is None
    assert not os.path.exists(os.path.join(str(tmp_path), "docs"))


def test_write_archmap_returns_none_for_empty_graph(tmp_path):
    pkg = tmp_path / "pkg"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    (pkg / "lonely.py").write_text("import os\n")
    assert write_archmap(str(tmp_path)) is None
    assert not os.path.exists(os.path.join(str(tmp_path), "docs"))


def test_engine_own_source_smoke():
    src = os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "src"))
    edges = module_graph(src)
    assert edges  # the engine's own module graph is never empty
    text = to_mermaid(edges)
    assert text
    assert "graph TD" in text
    assert "kickass_loop_engineer" in text
