"""Auto-diagram from finished code: stdlib ``ast`` import walk → mermaid.

Walks the workspace's Python package, collects internal module-to-module
import edges (stdlib and external imports excluded), and renders them as a
``graph TD`` mermaid diagram written to ``docs/architecture.mermaid.md`` at
every promote. Zero dependencies beyond the standard library.
"""

from __future__ import annotations

import ast
import logging
import os
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("kickass_loop_engineer.archmap")

ARCHMAP_RELPATH = os.path.join("docs", "architecture.mermaid.md")

_HEADER = (
    "<!-- generated by kickass-loop-engineer archmap; "
    "regenerated at every promote — do not edit by hand -->"
)


def _find_package(root: str) -> Tuple[Optional[str], Optional[str]]:
    """Return ``(package_name, package_dir)`` for the tree under *root*.

    Looks for the first top-level directory carrying an ``__init__.py``
    (alphabetical, hidden directories skipped), then falls back to the
    ``src/<pkg>`` layout. ``(None, None)`` when nothing is found.
    """
    for base in (root, os.path.join(root, "src")):
        try:
            entries = sorted(os.listdir(base))
        except OSError:
            continue
        for entry in entries:
            if entry.startswith(".") or entry == "src":
                continue
            candidate = os.path.join(base, entry)
            if os.path.isfile(os.path.join(candidate, "__init__.py")):
                return entry, candidate
    return None, None


def _collect_modules(package: str, pkg_dir: str) -> Dict[str, Tuple[str, bool]]:
    """Map each ``.py`` file path to ``(dotted module name, is_package)``."""
    modules: Dict[str, Tuple[str, bool]] = {}
    for dirpath, dirnames, filenames in os.walk(pkg_dir):
        dirnames[:] = [d for d in dirnames
                       if not d.startswith(".") and d != "__pycache__"]
        for filename in filenames:
            if not filename.endswith(".py"):
                continue
            path = os.path.join(dirpath, filename)
            rel = os.path.relpath(path, pkg_dir)
            parts = [package] + rel.split(os.sep)
            leaf = parts.pop()[: -len(".py")]
            is_package = leaf == "__init__"
            if not is_package:
                parts.append(leaf)
            modules[path] = (".".join(parts), is_package)
    return modules


def _resolve(candidates: List[str], known: set) -> Optional[str]:
    """Return the first candidate that names a known internal module."""
    for candidate in candidates:
        if candidate in known:
            return candidate
    return None


def _prefixes(dotted: str) -> List[str]:
    """Every dotted prefix of *dotted*, longest first."""
    parts = dotted.split(".")
    return [".".join(parts[:n]) for n in range(len(parts), 0, -1)]


def _import_targets(tree: ast.AST, module: str, is_package: bool,
                    package: str, known: set) -> List[str]:
    """Internal modules imported by *tree*, resolved against *known*."""
    targets: List[str] = []
    anchor_parts = module.split(".") if is_package else module.split(".")[:-1]
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name == package or alias.name.startswith(package + "."):
                    resolved = _resolve(_prefixes(alias.name), known)
                    if resolved:
                        targets.append(resolved)
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                up = node.level - 1
                if up > len(anchor_parts):
                    continue
                base_parts = list(anchor_parts[: len(anchor_parts) - up])
                if node.module:
                    base_parts = base_parts + node.module.split(".")
                base = ".".join(base_parts)
                if not base:
                    continue
            else:
                if not node.module:
                    continue
                if not (node.module == package
                        or node.module.startswith(package + ".")):
                    continue
                base = node.module
            for alias in node.names:
                resolved = _resolve([f"{base}.{alias.name}"] + _prefixes(base),
                                    known)
                if resolved:
                    targets.append(resolved)
    return targets


def module_graph(root: str) -> List[Tuple[str, str]]:
    """Build the internal import graph of the package under *root*.

    Args:
        root: Directory containing the package (directly or ``src/`` layout).

    Returns:
        Sorted, de-duplicated ``(importer, imported)`` dotted-module edges.
        Only edges between the package's own modules are included — stdlib
        and external imports are excluded. Files that fail to parse are
        skipped with a warning. Empty when no package is detected.
    """
    package, pkg_dir = _find_package(root)
    if not package or not pkg_dir:
        return []
    modules = _collect_modules(package, pkg_dir)
    known = {name for name, _is_pkg in modules.values()}
    edges: set = set()
    for path, (module, is_package) in modules.items():
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                tree = ast.parse(handle.read(), filename=path)
        except (SyntaxError, ValueError) as exc:
            logger.warning("archmap: skipping unparseable file %s: %s", path, exc)
            continue
        for target in _import_targets(tree, module, is_package, package, known):
            if target != module:
                edges.add((module, target))
    return sorted(edges)


def to_mermaid(edges: List[Tuple[str, str]]) -> str:
    """Render *edges* as a mermaid ``graph TD`` diagram.

    Node ids are sanitized (dots become underscores) while the visible label
    keeps the dotted module path.

    Args:
        edges: ``(importer, imported)`` dotted-module pairs.

    Returns:
        The mermaid diagram text (``graph TD`` with one line per edge).
    """
    def node(name: str) -> str:
        return f'{name.replace(".", "_")}["{name}"]'

    lines = ["graph TD"]
    lines.extend(f"    {node(src)} --> {node(dst)}" for src, dst in edges)
    return "\n".join(lines) + "\n"


def write_archmap(workspace: str) -> Optional[str]:
    """Regenerate ``docs/architecture.mermaid.md`` for *workspace*.

    Composes :func:`module_graph` and :func:`to_mermaid` and writes the
    result with a generated-by header. The file is fully rewritten each
    time, never appended.

    Args:
        workspace: The promoted workspace root.

    Returns:
        The written file's path, or ``None`` when the workspace has no
        detectable package or the module graph is empty (nothing written).
    """
    edges = module_graph(workspace)
    if not edges:
        logger.info("archmap: no internal module graph under %s; nothing written",
                    workspace)
        return None
    content = (
        f"{_HEADER}\n# Architecture map\n\n"
        f"```mermaid\n{to_mermaid(edges)}```\n"
    )
    path = os.path.join(workspace, ARCHMAP_RELPATH)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return path
